packages:
  - "examples/*"
  - "packages/*"

catalog:
  "@types/node": ^20.16.5
  "@vanilla-extract/css": ^1.15.3
  "@vanilla-extract/recipes": ^0.5.4
  "@vanilla-extract/vite-plugin": ^4.0.13
  "@vitejs/plugin-react": ^4.3.1
  eslint-plugin-import-access: ^2.2.2
  react: ^18.3.1
  react-dom: ^18.3.1
  typescript: ^5.6.2
  vite: ^5.4.1
